baseURL = 'https://whchi.github.io/'
theme = 'hamburg'
pygmentsCodeFences = true
### hanburg settings ###
defaultContentLanguageInSubdir = 'false'
defaultContentLanguage = 'zh'
disableLanguages = ['en', 'de']
paginate=5
[params]
# Short subtitle/tagline. This is displayed in the header.
# themecolor = '#ffff00' # Defines the tab color in Chrome for Android.
# To load additional CSS styles
customCSS = ['custom-hamburg.css']
mainSections=['posts']
# Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
ShowGDPRNotice = true
github = 'whchi'
linkedin='wei-han-chi-61500610'
disqus = true
disqusShortname = 'whcdc'
[mediaTypes]
  [mediaTypes."application/javascript"]
    suffixes = "js"
[languages]
    [languages.en]
        languageCode = 'en'
        languageName = 'English'
        title = 'murmurs and records'
        subtitle = ''
        copyright = '&copy; whchi 2018'
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = 'About'
                identifier = 'about'
                url = 'pages/about'
    [languages.zh]
        languageCode = 'zh-tw'
        languageName = '繁體中文'
        title = '雜談與紀錄'
        subtitle = 'that/s all'
        copyright = '&copy; whchi 2018'
        [languages.zh.menu]
            [[languages.zh.menu.main]]
                name = 'About'
                identifier = 'about'
                url = 'pages/about'


